import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    docsSidebar: [
        {
            type: 'html',
            value: `<a class="menu__link" href="/docs/openziti/learn/introduction">LEARN</a>`,
            className: 'sidebar-title',
        },
        {
            type: 'autogenerated',
            dirName: 'learn',
        },
        {
            type: 'html',
            value: `<a class="menu__link" href="/docs/openziti/reference">REFERENCE</a>`,
            className: 'sidebar-title',
        },
        {
            type: 'autogenerated',
            dirName: 'reference',
        },
        {
            type: 'html',
            value: `<a class="menu__link" href="/docs/openziti/guides">GUIDES</a>`,
            className: 'sidebar-title',
        },
        {
            type: 'autogenerated',
            dirName: 'guides',
        },
    ],
};

export default sidebars;
