/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'html',
      value: '<a class="menu__link" href="/docs/learn/introduction/">LEARN</a>', // The HTML to be rendered
      className: 'sidebar-title'
    },
    {
      type: 'autogenerated',
      dirName: 'learn',
    },
    {
      type: 'html',
      value: '<a class="menu__link" href="/docs/category/deployments">GUIDES</a>', // The HTML to be rendered
      className: 'sidebar-title'
    },
    {
      type: 'autogenerated',
      dirName: 'guides',
    },
    {
      type: 'html',
      value: '<a class="menu__link" href="/docs/reference/">REFERENCE</a>', // The HTML to be rendered
      className: 'sidebar-title'
    },
    {
      type: 'autogenerated',
      dirName: 'reference',
    },
  ],
};

module.exports = sidebars;
