import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    docsSidebar: [
        {type: 'html', value: `<a class="menu__link" href="/docs/openziti/learn/introduction">LEARN</a>`, className: 'sidebar-title'},
        {type: 'autogenerated', dirName: 'learn'},
        {type: 'html', value: `<a class="menu__link" href="/docs/openziti/reference">REFERENCE</a>`, className: 'sidebar-title'},
        {type: 'doc', id: 'reference/index'},
        {type: 'autogenerated', dirName: 'reference/ha'},
        {type: 'autogenerated', dirName: 'reference/tunnelers'},
        {type: 'autogenerated', dirName: 'reference/30-configuration'},
        {type: 'autogenerated', dirName: 'reference/40-command-line'},
        {type: 'autogenerated', dirName: 'reference/config-types'},
        'reference/logging',
        'reference/events',
        {
            type: 'category',
            label: 'Developer',
            items: [
                {type: 'doc', id: 'reference/developer/index'},
                {type: 'autogenerated', dirName: 'reference/developer/sdk'},
                {
                    type: 'category',
                    label: 'APIs',
                    items: [
                        {type: 'autogenerated', dirName: 'reference/developer/api'},
                        {type: 'link', label: 'Edge Client API reference', href: '/docs/openziti/reference/developer/api/edge-client-api-reference'},
                        {type: 'link', label: 'Edge Management API reference', href: '/docs/openziti/reference/developer/api/edge-management-api-reference'},
                    ],
                },
            ],
        },
        'reference/glossary',
        {type: 'html', value: `<a class="menu__link" href="/docs/openziti/guides">GUIDES</a>`, className: 'sidebar-title'},
        {type: 'autogenerated', dirName: 'guides'},
    ],
};

export default sidebars;
