version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/docusaurus"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    groups:
      all-deps:
        patterns:
          - "*"
